services:
  frontend:
    build: apps/spa-old
    depends_on:
      - backend
    restart: always

  backend:
    build: ./apps/backend
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=x64
      - DB_PASSWORD=password
      - DB_NAME=payextend_platform
      - SECRET=Yd8hPzX5qW3rT7gJ9kL2mN4bV6cX8jF1aS3dE5fG7hJ9kL2mN4bV6cX8
      - PORT=3000
      # Add other env vars (e.g., JWT secrets, FIREBASE credentials)
    depends_on:
      - db
    restart: always

  nginx:
    build: apps/spa-old
    ports:
      - "7000:80"
      - "9229:9229" # For Node.js debugging if needed
    volumes:
      - ./apps/spa/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend


  db:
    image: mariadb:10.11
    #image: mysql:8.1
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=payextend_platform
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Alpha.01$
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306"

  adminer:
    image: adminer
    ports:
      - "9090:8080"
    depends_on:
      - db

volumes:
  mariadb_data:
